name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type check
        run: npx vue-tsc --noEmit

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Generate hero screenshot
        if: success()
        run: |
          # Start the dev server in the background
          npm run dev &
          DEV_PID=$!

          # Wait for server to be ready
          echo "Waiting for dev server to start..."
          for i in {1..30}; do
            if curl -s http://localhost:5174 > /dev/null; then
              echo "Dev server is ready"
              break
            fi
            sleep 1
          done

          # Run screenshot test
          npx playwright test e2e/screenshot.spec.ts --reporter=line || echo "Screenshot test completed with status: $?"

          # Kill the dev server
          kill $DEV_PID || true
        continue-on-error: true

      - name: Upload screenshot artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hero-screenshot
          path: hero-screenshot.png
          if-no-files-found: ignore

      - name: Commit and push screenshot if changed
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f hero-screenshot.png ]; then
            git add hero-screenshot.png || true
            git diff --staged --quiet || git commit -m "Update hero screenshot [skip ci]" || true
            git push || echo "No changes to push"
          fi
        continue-on-error: true

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 7
