name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install sync-server dependencies
        run: |
          cd sync-server
          npm ci

      - name: Run TypeScript type check
        run: npx vue-tsc --noEmit

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

      - name: Run unit tests
        run: npm test

      - name: Check for code duplication
        run: npm run check:duplication

      - name: Check for dead code
        run: npm run check:dead-code
        continue-on-error: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Generate screenshots
        if: success()
        run: ./scripts/generate-screenshots.sh
        continue-on-error: true

      - name: Upload screenshots as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            hero-screenshot.png
            docs/images/*.png
          if-no-files-found: ignore
          retention-days: 30

      - name: Commit and push screenshots if changed
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hero-screenshot.png docs/images/*.png || true
          git diff --staged --quiet || git commit -m "Update screenshots [skip ci]" || true
          git push || echo "No changes to push"
        continue-on-error: true

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 7
